@TechForum.Api_HostAddress = http://localhost:5045

GET {{TechForum.Api_HostAddress}}/api/categories
Accept: application/json

###

GET {{TechForum.Api_HostAddress}}/api/categories/1
Accept: application/json

###

GET {{TechForum.Api_HostAddress}}/api/auth/antiforgery-token
Accept: application/json

###

GET {{TechForum.Api_HostAddress}}/api/auth/me
Accept: application/json

###

GET {{TechForum.Api_HostAddress}}/api/topics/1/answers?page=1&pageSize=20
Accept: application/json

###

PUT {{TechForum.Api_HostAddress}}/api/topics/1/answers/1/accepted
Accept: application/json

###
