export const appRoutes = {
  home: '/',
  articles: '/articles',
  questions: '/questions',
  write: '/write',
  myTopics: '/my-topics',
  saved: '/saved',
  account: '/account',
  adminReports: '/admin/reports',
  login: '/login',
  register: '/register',
  topic: (id: number | string) => `/topics/${encodeURIComponent(String(id))}`,
  editTopic: (id: number | string) => `/topics/${encodeURIComponent(String(id))}/edit`,
  member: (userId: string) => `/members/${encodeURIComponent(userId)}`,
} as const
