export const appRoutes = {
  home: '/',
  articles: '/articles',
  questions: '/questions',
  discussions: '/discussions',
  write: '/write',
  myTopics: '/my-topics',
  saved: '/saved',
  account: '/account',
  settings: '/settings',
  notifications: '/notifications',
  adminReports: '/admin/reports',
  adminCategories: '/admin/categories',
  adminTags: '/admin/tags',
  adminAccounts: '/admin/accounts',
  adminTopics: '/admin/topics',
  adminOverview: '/admin',
  login: '/login',
  register: '/register',
  topic: (id: number | string) => `/topics/${encodeURIComponent(String(id))}`,
  editTopic: (id: number | string) => `/topics/${encodeURIComponent(String(id))}/edit`,
  member: (userId: string) => `/members/${encodeURIComponent(userId)}`,
} as const
